---
default:
  image: "archlinux:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

check:
  stage: build
  needs: []
  before_script:
    - pacman -Syu --needed --noconfirm make ruby-mdl
  script:
    - cd site && make check

build:
  stage: build
  needs: []
  before_script:
    - pacman -Syu --needed --noconfirm make hugo git
  script:
    - cd site && make build
  artifacts:
    paths:
      - site/public

pages:
  stage: deploy
  needs:
    - check
    - build
  # tags:
  #   - secure
  script:
    - "true"
  artifacts:
    paths:
      - site/public
  # rules:
  #   - if: $CI_PROJECT_PATH == "archlinux/monthly-reports" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
