#!/usr/bin/env bash

function show() {
  echo "Checking version ... done!"
  lualatex -v
  arara -V
}

function run() {
  pushd src >/dev/null 2>&1
  echo "Generating PDFs ..."
  arara main.beamer main.report >/dev/null 2>&1
  popd >/dev/null 2>&1
}

function export() {
  [ -d pdf ] || mkdir -p pdf
  mv src/main.*.pdf pdf
  echo "PDFs are in"
  ls pdf
}

# show
run
export
