#!/usr/bin/env bash

# shellcheck disable=SC2164

function show() {
  echo "Checking version ... done!"
  lualatex -v
  arara -V
}

function run() {
  git pull >/dev/null 2>&1
  pushd src/TeX/notes >/dev/null 2>&1
  echo "Generating PDFs ..."
  arara -v main.beamer main.report #>/dev/null 2>&1
  popd >/dev/null 2>&1
  pushd src/TeX/thesis >/dev/null 2>&1
  arara -v main #>/dev/null 2>&1
  popd >/dev/null 2>&1
}

function export() {
  [ -d pdf ] || mkdir -p pdf
  mv src/TeX/notes/main.*.pdf pdf
  mv src/TeX/thesis/main*.pdf pdf
  echo "PDFs are in pdf directory"
  ls pdf
}

#show
run
export
