#!/usr/bin/env bash

function show() {
  echo "Checking version ... done!"
  lualatex -v
  arara -V
}

function run() {
  git pull >/dev/null 2>&1
  pushd src/TeX >/dev/null 2>&1
  echo "Generating PDFs ..."
  arara main.beamer main.report >/dev/null 2>&1
  popd >/dev/null 2>&1
}

function export() {
  [ -d pdf ] || mkdir -p pdf && mv src/TeX/main.*.pdf pdf
  echo "PDFs are in pdf directory"
  ls pdf
}

# show
run
export
